// resuma-routes-fingerprint: b5637803f99c9f3f
// Auto-generated by `resuma routes --generate`. Do not edit by hand.
use resuma::prelude::*;
use resuma::FlowPageRegistry;

pub struct PagesRegistry;

impl FlowPageRegistry for PagesRegistry {
    fn routes(&self) -> &'static [(&'static str, &'static str)] {
        &[
            ("/", "index"),
            ("/docs", "docs"),
            ("/docs/api", "docs::api"),
            ("/docs/architecture", "docs::architecture"),
            ("/docs/benchmark", "docs::benchmark"),
            ("/docs/cli", "docs::cli"),
            ("/docs/components", "docs::components"),
            ("/docs/components/client", "docs::components::client"),
            ("/docs/components/context", "docs::components::context"),
            (
                "/docs/components/control_flow",
                "docs::components::control_flow",
            ),
            (
                "/docs/components/desktop_ui",
                "docs::components::desktop_ui",
            ),
            ("/docs/components/effects", "docs::components::effects"),
            (
                "/docs/components/error_boundary",
                "docs::components::error_boundary",
            ),
            ("/docs/components/form", "docs::components::form"),
            ("/docs/components/gesture", "docs::components::gesture"),
            ("/docs/components/handlers", "docs::components::handlers"),
            ("/docs/components/islands", "docs::components::islands"),
            ("/docs/components/js", "docs::components::js"),
            ("/docs/components/modal", "docs::components::modal"),
            ("/docs/components/nav_link", "docs::components::nav_link"),
            ("/docs/components/popup", "docs::components::popup"),
            ("/docs/components/server", "docs::components::server"),
            ("/docs/components/signals", "docs::components::signals"),
            ("/docs/components/slots", "docs::components::slots"),
            ("/docs/components/store", "docs::components::store"),
            ("/docs/components/tasks", "docs::components::tasks"),
            ("/docs/components/testing", "docs::components::testing"),
            ("/docs/components/view", "docs::components::view"),
            (
                "/docs/components/virtual_for",
                "docs::components::virtual_for",
            ),
            ("/docs/cookbook", "docs::cookbook"),
            ("/docs/cookbook/debouncer", "docs::cookbook::debouncer"),
            ("/docs/cookbook/deploy", "docs::cookbook::deploy"),
            ("/docs/cookbook/docker", "docs::cookbook::docker"),
            (
                "/docs/cookbook/loader_invalidation",
                "docs::cookbook::loader_invalidation",
            ),
            ("/docs/cookbook/portals", "docs::cookbook::portals"),
            ("/docs/cookbook/prg", "docs::cookbook::prg"),
            (
                "/docs/cookbook/streaming_loaders",
                "docs::cookbook::streaming_loaders",
            ),
            ("/docs/cookbook/theme", "docs::cookbook::theme"),
            (
                "/docs/cookbook/view_transitions",
                "docs::cookbook::view_transitions",
            ),
            ("/docs/examples", "docs::examples"),
            ("/docs/exec", "docs::exec"),
            ("/docs/exec/flow_ui", "docs::exec::flow_ui"),
            ("/docs/exec/ops", "docs::exec::ops"),
            ("/docs/exec/queue", "docs::exec::queue"),
            ("/docs/exec/scheduler", "docs::exec::scheduler"),
            ("/docs/exec/security", "docs::exec::security"),
            ("/docs/exec/tools", "docs::exec::tools"),
            ("/docs/exec/webhooks", "docs::exec::webhooks"),
            ("/docs/exec/workers", "docs::exec::workers"),
            ("/docs/faq", "docs::faq"),
            ("/docs/flow", "docs::flow"),
            ("/docs/flow/caching", "docs::flow::caching"),
            ("/docs/flow/endpoints", "docs::flow::endpoints"),
            ("/docs/flow/errors", "docs::flow::errors"),
            ("/docs/flow/layouts", "docs::flow::layouts"),
            ("/docs/flow/loaders", "docs::flow::loaders"),
            ("/docs/flow/middleware", "docs::flow::middleware"),
            ("/docs/flow/pages", "docs::flow::pages"),
            ("/docs/flow/prefetch", "docs::flow::prefetch"),
            ("/docs/flow/pwa", "docs::flow::pwa"),
            ("/docs/flow/query_params", "docs::flow::query_params"),
            ("/docs/flow/routing", "docs::flow::routing"),
            ("/docs/flow/streaming", "docs::flow::streaming"),
            ("/docs/flow/submits", "docs::flow::submits"),
            ("/docs/getting_started", "docs::getting_started"),
            ("/docs/integrations", "docs::integrations"),
            (
                "/docs/integrations/ai_assistant",
                "docs::integrations::ai_assistant",
            ),
            ("/docs/integrations/auth", "docs::integrations::auth"),
            ("/docs/integrations/e2e", "docs::integrations::e2e"),
            ("/docs/integrations/i18n", "docs::integrations::i18n"),
            (
                "/docs/integrations/og_image",
                "docs::integrations::og_image",
            ),
            ("/docs/integrations/seo_geo", "docs::integrations::seo_geo"),
            ("/docs/integrations/sqlx", "docs::integrations::sqlx"),
            (
                "/docs/integrations/supabase",
                "docs::integrations::supabase",
            ),
            (
                "/docs/integrations/tailwind",
                "docs::integrations::tailwind",
            ),
            ("/docs/integrations/turso", "docs::integrations::turso"),
            (
                "/docs/integrations/validator",
                "docs::integrations::validator",
            ),
            ("/docs/package", "docs::package"),
            ("/docs/project_structure", "docs::project_structure"),
            ("/docs/reactivity", "docs::reactivity"),
            ("/docs/search", "docs::search"),
            ("/docs/security", "docs::security"),
            (
                "/docs/security/authorization",
                "docs::security::authorization",
            ),
            (
                "/docs/security/backend_patterns",
                "docs::security::backend_patterns",
            ),
            ("/docs/security/configure", "docs::security::configure"),
            ("/docs/security/environment", "docs::security::environment"),
            ("/docs/security/middleware", "docs::security::middleware"),
            (
                "/docs/security/server_actions",
                "docs::security::server_actions",
            ),
            ("/docs/security/todo", "docs::security::todo"),
        ]
    }

    fn layout_for(&self, pattern: &str) -> &'static [&'static str] {
        match pattern {
            "/" => &["/"],
            "/docs" => &["/", "/docs"],
            "/docs/api" => &["/", "/docs"],
            "/docs/architecture" => &["/", "/docs"],
            "/docs/benchmark" => &["/", "/docs"],
            "/docs/cli" => &["/", "/docs"],
            "/docs/components" => &["/", "/docs"],
            "/docs/components/client" => &["/", "/docs"],
            "/docs/components/context" => &["/", "/docs"],
            "/docs/components/control_flow" => &["/", "/docs"],
            "/docs/components/desktop_ui" => &["/", "/docs"],
            "/docs/components/effects" => &["/", "/docs"],
            "/docs/components/error_boundary" => &["/", "/docs"],
            "/docs/components/form" => &["/", "/docs"],
            "/docs/components/gesture" => &["/", "/docs"],
            "/docs/components/handlers" => &["/", "/docs"],
            "/docs/components/islands" => &["/", "/docs"],
            "/docs/components/js" => &["/", "/docs"],
            "/docs/components/modal" => &["/", "/docs"],
            "/docs/components/nav_link" => &["/", "/docs"],
            "/docs/components/popup" => &["/", "/docs"],
            "/docs/components/server" => &["/", "/docs"],
            "/docs/components/signals" => &["/", "/docs"],
            "/docs/components/slots" => &["/", "/docs"],
            "/docs/components/store" => &["/", "/docs"],
            "/docs/components/tasks" => &["/", "/docs"],
            "/docs/components/testing" => &["/", "/docs"],
            "/docs/components/view" => &["/", "/docs"],
            "/docs/components/virtual_for" => &["/", "/docs"],
            "/docs/cookbook" => &["/", "/docs"],
            "/docs/cookbook/debouncer" => &["/", "/docs"],
            "/docs/cookbook/deploy" => &["/", "/docs"],
            "/docs/cookbook/docker" => &["/", "/docs"],
            "/docs/cookbook/loader_invalidation" => &["/", "/docs"],
            "/docs/cookbook/portals" => &["/", "/docs"],
            "/docs/cookbook/prg" => &["/", "/docs"],
            "/docs/cookbook/streaming_loaders" => &["/", "/docs"],
            "/docs/cookbook/theme" => &["/", "/docs"],
            "/docs/cookbook/view_transitions" => &["/", "/docs"],
            "/docs/examples" => &["/", "/docs"],
            "/docs/exec" => &["/", "/docs"],
            "/docs/exec/flow_ui" => &["/", "/docs"],
            "/docs/exec/ops" => &["/", "/docs"],
            "/docs/exec/queue" => &["/", "/docs"],
            "/docs/exec/scheduler" => &["/", "/docs"],
            "/docs/exec/security" => &["/", "/docs"],
            "/docs/exec/tools" => &["/", "/docs"],
            "/docs/exec/webhooks" => &["/", "/docs"],
            "/docs/exec/workers" => &["/", "/docs"],
            "/docs/faq" => &["/", "/docs"],
            "/docs/flow" => &["/", "/docs"],
            "/docs/flow/caching" => &["/", "/docs"],
            "/docs/flow/endpoints" => &["/", "/docs"],
            "/docs/flow/errors" => &["/", "/docs"],
            "/docs/flow/layouts" => &["/", "/docs"],
            "/docs/flow/loaders" => &["/", "/docs"],
            "/docs/flow/middleware" => &["/", "/docs"],
            "/docs/flow/pages" => &["/", "/docs"],
            "/docs/flow/prefetch" => &["/", "/docs"],
            "/docs/flow/pwa" => &["/", "/docs"],
            "/docs/flow/query_params" => &["/", "/docs"],
            "/docs/flow/routing" => &["/", "/docs"],
            "/docs/flow/streaming" => &["/", "/docs"],
            "/docs/flow/submits" => &["/", "/docs"],
            "/docs/getting_started" => &["/", "/docs"],
            "/docs/integrations" => &["/", "/docs"],
            "/docs/integrations/ai_assistant" => &["/", "/docs"],
            "/docs/integrations/auth" => &["/", "/docs"],
            "/docs/integrations/e2e" => &["/", "/docs"],
            "/docs/integrations/i18n" => &["/", "/docs"],
            "/docs/integrations/og_image" => &["/", "/docs"],
            "/docs/integrations/seo_geo" => &["/", "/docs"],
            "/docs/integrations/sqlx" => &["/", "/docs"],
            "/docs/integrations/supabase" => &["/", "/docs"],
            "/docs/integrations/tailwind" => &["/", "/docs"],
            "/docs/integrations/turso" => &["/", "/docs"],
            "/docs/integrations/validator" => &["/", "/docs"],
            "/docs/package" => &["/", "/docs"],
            "/docs/project_structure" => &["/", "/docs"],
            "/docs/reactivity" => &["/", "/docs"],
            "/docs/search" => &["/", "/docs"],
            "/docs/security" => &["/", "/docs"],
            "/docs/security/authorization" => &["/", "/docs"],
            "/docs/security/backend_patterns" => &["/", "/docs"],
            "/docs/security/configure" => &["/", "/docs"],
            "/docs/security/environment" => &["/", "/docs"],
            "/docs/security/middleware" => &["/", "/docs"],
            "/docs/security/server_actions" => &["/", "/docs"],
            "/docs/security/todo" => &["/", "/docs"],
            _ => &[],
        }
    }

    fn render(&self, module: &str, req: FlowRequest) -> Option<View> {
        match module {
            "index" => Some(super::index::page(req)),
            "docs" => Some(super::docs::index::page(req)),
            "docs::api" => Some(super::docs::api::page(req)),
            "docs::architecture" => Some(super::docs::architecture::page(req)),
            "docs::benchmark" => Some(super::docs::benchmark::page(req)),
            "docs::cli" => Some(super::docs::cli::page(req)),
            "docs::components" => Some(super::docs::components::index::page(req)),
            "docs::components::client" => Some(super::docs::components::client::page(req)),
            "docs::components::context" => Some(super::docs::components::context::page(req)),
            "docs::components::control_flow" => {
                Some(super::docs::components::control_flow::page(req))
            }
            "docs::components::desktop_ui" => Some(super::docs::components::desktop_ui::page(req)),
            "docs::components::effects" => Some(super::docs::components::effects::page(req)),
            "docs::components::error_boundary" => {
                Some(super::docs::components::error_boundary::page(req))
            }
            "docs::components::form" => Some(super::docs::components::form::page(req)),
            "docs::components::gesture" => Some(super::docs::components::gesture::page(req)),
            "docs::components::handlers" => Some(super::docs::components::handlers::page(req)),
            "docs::components::islands" => Some(super::docs::components::islands::page(req)),
            "docs::components::js" => Some(super::docs::components::js::page(req)),
            "docs::components::modal" => Some(super::docs::components::modal::page(req)),
            "docs::components::nav_link" => Some(super::docs::components::nav_link::page(req)),
            "docs::components::popup" => Some(super::docs::components::popup::page(req)),
            "docs::components::server" => Some(super::docs::components::server::page(req)),
            "docs::components::signals" => Some(super::docs::components::signals::page(req)),
            "docs::components::slots" => Some(super::docs::components::slots::page(req)),
            "docs::components::store" => Some(super::docs::components::store::page(req)),
            "docs::components::tasks" => Some(super::docs::components::tasks::page(req)),
            "docs::components::testing" => Some(super::docs::components::testing::page(req)),
            "docs::components::view" => Some(super::docs::components::view::page(req)),
            "docs::components::virtual_for" => {
                Some(super::docs::components::virtual_for::page(req))
            }
            "docs::cookbook" => Some(super::docs::cookbook::index::page(req)),
            "docs::cookbook::debouncer" => Some(super::docs::cookbook::debouncer::page(req)),
            "docs::cookbook::deploy" => Some(super::docs::cookbook::deploy::page(req)),
            "docs::cookbook::docker" => Some(super::docs::cookbook::docker::page(req)),
            "docs::cookbook::loader_invalidation" => {
                Some(super::docs::cookbook::loader_invalidation::page(req))
            }
            "docs::cookbook::portals" => Some(super::docs::cookbook::portals::page(req)),
            "docs::cookbook::prg" => Some(super::docs::cookbook::prg::page(req)),
            "docs::cookbook::streaming_loaders" => {
                Some(super::docs::cookbook::streaming_loaders::page(req))
            }
            "docs::cookbook::theme" => Some(super::docs::cookbook::theme::page(req)),
            "docs::cookbook::view_transitions" => {
                Some(super::docs::cookbook::view_transitions::page(req))
            }
            "docs::examples" => Some(super::docs::examples::page(req)),
            "docs::exec" => Some(super::docs::exec::index::page(req)),
            "docs::exec::flow_ui" => Some(super::docs::exec::flow_ui::page(req)),
            "docs::exec::ops" => Some(super::docs::exec::ops::page(req)),
            "docs::exec::queue" => Some(super::docs::exec::queue::page(req)),
            "docs::exec::scheduler" => Some(super::docs::exec::scheduler::page(req)),
            "docs::exec::security" => Some(super::docs::exec::security::page(req)),
            "docs::exec::tools" => Some(super::docs::exec::tools::page(req)),
            "docs::exec::webhooks" => Some(super::docs::exec::webhooks::page(req)),
            "docs::exec::workers" => Some(super::docs::exec::workers::page(req)),
            "docs::faq" => Some(super::docs::faq::page(req)),
            "docs::flow" => Some(super::docs::flow::index::page(req)),
            "docs::flow::caching" => Some(super::docs::flow::caching::page(req)),
            "docs::flow::endpoints" => Some(super::docs::flow::endpoints::page(req)),
            "docs::flow::errors" => Some(super::docs::flow::errors::page(req)),
            "docs::flow::layouts" => Some(super::docs::flow::layouts::page(req)),
            "docs::flow::loaders" => Some(super::docs::flow::loaders::page(req)),
            "docs::flow::middleware" => Some(super::docs::flow::middleware::page(req)),
            "docs::flow::pages" => Some(super::docs::flow::pages::page(req)),
            "docs::flow::prefetch" => Some(super::docs::flow::prefetch::page(req)),
            "docs::flow::pwa" => Some(super::docs::flow::pwa::page(req)),
            "docs::flow::query_params" => Some(super::docs::flow::query_params::page(req)),
            "docs::flow::routing" => Some(super::docs::flow::routing::page(req)),
            "docs::flow::streaming" => Some(super::docs::flow::streaming::page(req)),
            "docs::flow::submits" => Some(super::docs::flow::submits::page(req)),
            "docs::getting_started" => Some(super::docs::getting_started::page(req)),
            "docs::integrations" => Some(super::docs::integrations::index::page(req)),
            "docs::integrations::ai_assistant" => {
                Some(super::docs::integrations::ai_assistant::page(req))
            }
            "docs::integrations::auth" => Some(super::docs::integrations::auth::page(req)),
            "docs::integrations::e2e" => Some(super::docs::integrations::e2e::page(req)),
            "docs::integrations::i18n" => Some(super::docs::integrations::i18n::page(req)),
            "docs::integrations::og_image" => Some(super::docs::integrations::og_image::page(req)),
            "docs::integrations::seo_geo" => Some(super::docs::integrations::seo_geo::page(req)),
            "docs::integrations::sqlx" => Some(super::docs::integrations::sqlx::page(req)),
            "docs::integrations::supabase" => Some(super::docs::integrations::supabase::page(req)),
            "docs::integrations::tailwind" => Some(super::docs::integrations::tailwind::page(req)),
            "docs::integrations::turso" => Some(super::docs::integrations::turso::page(req)),
            "docs::integrations::validator" => {
                Some(super::docs::integrations::validator::page(req))
            }
            "docs::package" => Some(super::docs::package::page(req)),
            "docs::project_structure" => Some(super::docs::project_structure::page(req)),
            "docs::reactivity" => Some(super::docs::reactivity::page(req)),
            "docs::search" => Some(super::docs::search::page(req)),
            "docs::security" => Some(super::docs::security::index::page(req)),
            "docs::security::authorization" => {
                Some(super::docs::security::authorization::page(req))
            }
            "docs::security::backend_patterns" => {
                Some(super::docs::security::backend_patterns::page(req))
            }
            "docs::security::configure" => Some(super::docs::security::configure::page(req)),
            "docs::security::environment" => Some(super::docs::security::environment::page(req)),
            "docs::security::middleware" => Some(super::docs::security::middleware::page(req)),
            "docs::security::server_actions" => {
                Some(super::docs::security::server_actions::page(req))
            }
            "docs::security::todo" => Some(super::docs::security::todo::page(req)),
            _ => None,
        }
    }
}
