// Auto-generated by `resuma routes --generate`. Do not edit by hand.

pub mod docs {
    pub mod api;
    pub mod architecture;
    pub mod benchmark;
    pub mod cli;
    pub mod components {
        pub mod client;
        pub mod context;
        pub mod control_flow;
        pub mod desktop_ui;
        pub mod effects;
        pub mod error_boundary;
        pub mod form;
        pub mod gesture;
        pub mod handlers;
        pub mod index;
        pub mod islands;
        pub mod js;
        pub mod modal;
        pub mod nav_link;
        pub mod popup;
        pub mod server;
        pub mod signals;
        pub mod slots;
        pub mod store;
        pub mod tasks;
        pub mod testing;
        pub mod view;
        pub mod virtual_for;
    }
    pub mod cookbook {
        pub mod debouncer;
        pub mod deploy;
        pub mod docker;
        pub mod index;
        pub mod loader_invalidation;
        pub mod portals;
        pub mod prg;
        pub mod streaming_loaders;
        pub mod theme;
        pub mod view_transitions;
    }
    pub mod examples;
    pub mod exec {
        pub mod flow_ui;
        pub mod index;
        pub mod ops;
        pub mod queue;
        pub mod scheduler;
        pub mod security;
        pub mod tools;
        pub mod webhooks;
        pub mod workers;
    }
    pub mod faq;
    pub mod flow {
        pub mod caching;
        pub mod endpoints;
        pub mod errors;
        pub mod index;
        pub mod layouts;
        pub mod loaders;
        pub mod middleware;
        pub mod pages;
        pub mod prefetch;
        pub mod pwa;
        pub mod query_params;
        pub mod routing;
        pub mod streaming;
        pub mod submits;
    }
    pub mod getting_started;
    pub mod index;
    pub mod integrations {
        pub mod ai_assistant;
        pub mod auth;
        pub mod e2e;
        pub mod i18n;
        pub mod index;
        pub mod og_image;
        pub mod seo_geo;
        pub mod sqlx;
        pub mod supabase;
        pub mod tailwind;
        pub mod turso;
        pub mod validator;
    }
    pub mod package;
    pub mod project_structure;
    pub mod reactivity;
    pub mod search;
    pub mod security {
        pub mod authorization;
        pub mod backend_patterns;
        pub mod configure;
        pub mod environment;
        pub mod index;
        pub mod middleware;
        pub mod server_actions;
        pub mod todo;
    }
}
pub mod index;

mod _registry;
pub use _registry::PagesRegistry;
