use crate::site::code_block;
use resuma::prelude::*;

pub fn page(_req: FlowRequest) -> View {
    view! {
        <>
            <h1>"Configure security"</h1>
            <p class="lead">"Tune Resuma's HTTP hardening from Rust or environment variables."</p>

            {crate::site::demos::security_configure()}

            <h2>"ServeOptions + SecurityConfig"</h2>
            {code_block(r#"use resuma::prelude::*;

pub fn serve_options() -> ServeOptions {
    ServeOptions {
        addr: "127.0.0.1:3000".parse().unwrap(),
        security: SecurityConfig {
            csrf: true,
            origin_check: true,
            trust_proxy: true,          // Fly.io / nginx
            body_limit_bytes: 256 * 1024,
            actions_per_minute: 90,
            submits_per_minute: 45,
            hide_benchmark: true,
            production: true,
        },
    }
}

#[tokio::main]
async fn main() -> std::io::Result<()> {
    ResumaApp::new()
        .page("/", || page())
        .serve(serve_options())
        .await
}"#)}

            <h2>"Environment variables"</h2>
            <p>
                "Local dev needs no env vars — " <code>"cargo run"</code> " and " <code>"resuma dev"</code> " use secure defaults. "
                "For production, " <code>"SecurityConfig::from_env()"</code> " reads "
                <code>"RESUMA_ENV"</code> ", " <code>"RESUMA_TRUST_PROXY"</code> ", rate limits, and CSP flags."
            </p>
            <p>
                <strong>"Full guide:"</strong> " "
                <a href="/docs/security/environment">"Environment variables"</a> " — what you need by app type (SSR vs workers), "
                "automatic vs manual setup, Fly scaffold, and " <code>"resuma doctor"</code>"."
            </p>
            {code_block(r#"RESUMA_CSRF=1              # default on
RESUMA_ORIGIN_CHECK=1      # default on
RESUMA_BODY_LIMIT=1048576
RESUMA_RATE_ACTIONS=120
RESUMA_RATE_SUBMITS=60
RESUMA_RATE_BACKEND=memory|disk   # disk auto when RESUMA_ENV=production
RESUMA_DATA_DIR=/data/resuma      # persistent volume for disk rate limits + exec"#)}

            <h2>"Built-in rate limiting (no Redis)"</h2>
            <p>
                "Resuma includes per-IP rate limiting for actions, submits, and exec routes. "
                "Dev uses memory; production uses " <code>"{RESUMA_DATA_DIR}/rate-limit/"</code> " with "
                "file locks — shared across processes on the same volume. "
                "For multi-region deploys without a shared disk, add edge rate limiting "
                "(nginx, Fly proxy, Cloudflare) instead of an external datastore."
            </p>

            <h2>"Resuma OS (exec layer)"</h2>
            <p>
                "Worker, queue, graph, scheduler, and webhook routes need "
                <code>"RESUMA_EXEC_API_KEY"</code> " in production (fail-closed without it). "
                "See " <a href="/docs/security/environment">"Environment variables"</a> " · "
                <a href="/docs/exec/security">"Exec security"</a> " · "
                <a href="/docs/exec/ops">"Ops & production"</a>"."
            </p>

            <h2>"CSP (Qwik-style, stronger defaults)"</h2>
            <p>
                "Like Qwik City's " <code>"plugin@csp.ts"</code> ", Resuma sets CSP on every SSR response — but uses a "
                <strong>"crypto nonce"</strong> " per request (not " <code>"Date.now()"</code> "), adds "
                <code>"'strict-dynamic'"</code> " on scripts, and skips CSP in dev when " <code>"RESUMA_DEV=1"</code> " unless "
                <code>"RESUMA_CSP_DEV=1"</code> "."
            </p>
            <p>
                "Inline " <code>"&lt;style&gt;"</code> " / " <code>"&lt;script&gt;"</code> " in "
                <code>"with_head()"</code> " get the nonce automatically. Host images on "
                <code>"'self'"</code> " via " <code>"public/images/…"</code> " (see "
                <a href="/docs/flow/pwa">"PWA & public/"</a>"), "
                <code>"static_asset"</code> ", or extend " <code>"CspConfig::img_src"</code> "."
            </p>
            {code_block(r##"FlowApp::new()
    .with_head("<style>.hero { color: var(--accent); }</style>")
    .serve(FlowServeOptions {
        security: SecurityConfig {
            csp: CspConfig::production(["https://images.pexels.com"]),
            ..SecurityConfig::from_env()
        },
        ..FlowServeOptions::default()
    })"##)}
            <p>"Environment: " <code>"RESUMA_CSP=0"</code> ", " <code>"RESUMA_CSP_IMG_SRC=https://cdn.example.com"</code> ", "
                <code>"RESUMA_CSP_REPORT_ONLY=1"</code> ". Validate at "
                <a href="https://csp-evaluator.withgoogle.com/" target="_blank" rel="noopener">"csp-evaluator.withgoogle.com"</a>"."</p>

            <h2>"Flow apps"</h2>
            {code_block(r#"use pages::PagesRegistry; // generated by resuma routes --generate

FlowApp::new()
    .auto_pages("src/pages", PagesRegistry)
    .serve(FlowServeOptions {
        addr: ([0, 0, 0, 0], 3000).into(),
        security: SecurityConfig::from_env(),
    })
    .await"#)}

            <h2>"Fly.io"</h2>
            <p>
                "Production deploy (Fly, DigitalOcean, Docker): "
                <a href="/docs/cookbook/deploy">"Deploy cookbook"</a>". "
                "This repo ships a working Fly config at the workspace root — live at "
                <a href="https://resuma-docs.fly.dev/" target="_blank">"resuma-docs.fly.dev"</a>"."
            </p>
            {code_block(r#"# fly.toml [env] — minimum for production
RESUMA_ENV = "production"
RESUMA_TRUST_PROXY = "1"
RESUMA_TRUSTED_PROXY_CIDRS = "fdaa::/16"
SITE_URL = "https://your-app.fly.dev"
HOST = "0.0.0.0"
PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true"#)}

            <h2>"Security checklist before deploy"</h2>
            <ul>
                <li><code>"RESUMA_ENV=production"</code> " — sanitized errors"</li>
                <li><code>"RESUMA_TRUST_PROXY=1"</code> " — real client IP + HTTPS detection"</li>
                <li><code>"force_https = true"</code> " on Fly / reverse proxy"</li>
                <li>"Run container as non-root (see Dockerfile)"</li>
                <li>"Auth + validation on sensitive " <code>"#[server]"</code> " actions — " <a href="/docs/security/todo">"todo example"</a></li>
            </ul>
        </>
    }
}
